[meta]
tags = ['parser', 'dbsave']

#[settings]
#chebi_attr_etc = ['quality','chebi_star','lipidmaps_class_id','ch_iupac_name']

[names_mapping]
names = ["IUPAC_NAME", "SYNONYM", "ChEBI NAME"]

[attribute_mapping]
'chebi id' = 'chebi_id'
'secondary chebi id' = 'chebi_id_alt'

formulae = 'formula'
inchi = 'inchi'
inchikey = 'inchikey'
smiles = 'smiles'

definition = 'description'
'kegg compound database links' = 'kegg_id'
'pubmed citation links' = 'pubmed_id'
#'cas registry numbers' = 'cas_id'

'pubchem substance database links' = 'pubchem_substance_id'
'pubchem compound database links' = 'pubchem_id'
'lipid maps instance database links' = 'lipmaps_instance_id'
'lipid maps class database links' = 'lipmaps_class_id'
'lipid maps database links' = 'lipmaps_id'

'virtual metabolic human database links' = 'vmhdb_id'
'drugbank metabolite database links' = 'drugbank_id'
'chinese abstracts database links' = 'chinese_abstracts_id'
'carotenoids database database links' = 'carotenoids_id'
'carotenoids database links' = 'carotenoids_id'
'fao/who standards database links' = 'fao_who_id'

"wikipedia" = "wiki_id"
'wikipedia database links' = 'wiki_id'

star = 'chebi_star'
chebi_star = 'chebi_star'
'chebi star' = 'chebi_star'
charge = 'charge'
mass = 'mass'
'monoisotopic mass' = 'mi_mass'
'monoisotopic_mass' = 'mi_mass'

