[meta]
tags = ['parser', 'dbsave']

[settings]
chebi_attr_etc = ['quality','chebi_star','lipidmaps_class_id','ch_iupac_name']

[attribute_mapping]
'ChEBI ID' = 'chebi_id'
'Secondary ChEBI ID' = 'chebi_id_alt'

'ChEBI Name' = 'names'
'ChEBI NAME' = 'names'
'IUPAC Names' = 'names'
Synonyms = 'names'

Formulae = 'formula'
InChI = 'inchi'
InChIKey = 'inchikey'
SMILES = 'smiles'

Definition = 'description'
'PubChem Database Links' = 'pubchem_id'
'KEGG COMPOUND Database Links' = 'kegg_id'
'HMDB Database Links' = 'hmdb_id'
'LIPID MAPS instance Database Links' = 'lipmaps_id'
'LIPID MAPS class Database Links' = 'lipmaps_id'
'CAS Registry Numbers' = 'cas_id'
'Chemspider Database Links' = 'chemspider_id'

'PubMed citation Links' = 'pubmed_id'
'PDB Database Links' = 'pdb_id'
'UniProt Database Links' = 'uniprot_id'
'SwissLipids Database Links' = 'swisslipids_id'
'Wikipedia Database Links' = 'wiki_id'
'DrugBank Database Links' = 'drugbank_id'

Star = 'chebi_star'
star = 'chebi_star'
Charge = 'charge'
Mass = 'mass'
'Monoisotopic Mass' = 'mi_mass'

