[db]
autocommit = 'no'
db_type = "parquet"

[driver_asyncpg]
pool_size = [10, 10]
single_connection = false
max_cached_statement_lifetime = 0
statement_cache_size = 0 #300

[driver_psycopg]

[driver_sqlalchemy]

[conn_postgresql]
dsn = 'postgres://postgres:postgres@localhost/mfdb'

[conn_sqlite]
dsn = 'sqlite:///mfdb_discovery.db'

[conn_parquet]
file = "mfdb.parquet"
