[meta]
tags = ['parser', 'dbsave', 'api', 'mapping']

[attributes]
hmdb_attr_etc = ['state']

[attribute_mapping]
accession = 'hmdb_id'
secondary_accessions = 'hmdb_id_alt'

name = 'names'
iupac_name = 'names'
traditional_iupac = 'names'
synonyms = 'names'

# description = 'description'
#state = 'state'

formal_charge = 'charge'
average_molecular_weight = 'mass'
avg_mol_weight = 'mass'
monoisotopic_molecular_weight = 'mi_mass'
monoisotopic_mol_weight = 'mi_mass'
monisotopic_molecular_weight = 'mi_mass'
monisotopic_mol_weight = 'mi_mass'
chemical_formula = 'formula'
#smiles = 'smiles'
#inchi = 'inchi'
#inchikey = 'inchikey'

cas_registry_number = 'cas_id'
pubchem_compound_id = 'pubchem_id'
wikipedia_id = 'wiki_id'
